swagger: "3.0"
info:
  version: 1.0.0
  title: Herc UI
  description: "Swagger for Herc UI"
  termsOfService:
  contact:
    name:
    email:
    url:
host:
basePath: /
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json

tags:
  - name: Companies
  - name: Projects
  - name: Appointments
  - name: Volunteers
  - name: Works

responses:
  NotFound:
    description: Resource was not found
    schema:
      allOf:
        - $ref: "./definitions/index.yaml#/definitions/Error"
      type: object
      required:
        - status
      properties:
        status:
          type: integer
          format: int32
          default: 404

parameters:
  resourceId:
    name: id
    in: path
    type: string
    description: "The resource identifier string"
    required: true

paths:
   /:
      get:
        tags:
          - Index
        summary: "Index"
        operationId: getIndex
        responses:
          "200":
            description: "Index of all api calls"
            schema:
              $ref: "./definitions/entities/index.yaml#/definitions/EntitiesIndex"
